version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: re-mind-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data:/qdrant/storage
      - ./snapshots:/qdrant/snapshots
      - ./config/production.yaml:/qdrant/config/production.yaml
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_data:
    driver: local
  qdrant_snapshots:
    driver: local